services:
  mosquitto:
    build: .
    container_name: mosquitto
    ports:
      - "1883:1883" # Mở cổng MQTT
    environment:
      MQTT_USER: "your_username"       # Thay bằng username của bạn
      MQTT_PASSWORD: "your_password"   # Thay bằng password của bạn
    volumes:
      - ./mosquitto_data:/mosquitto/data
      - ./mosquitto_log:/mosquitto/log
