services:
  mosquitto:
    image: nguyendkn/mosquitto
    container_name: mosquitto
    ports:
      - "1883:1883"
    environment:
      MQTT_USER: "your_username"
      MQTT_PASSWORD: "your_password"
    volumes:
      - ./mosquitto_data:/mosquitto/data
      - ./mosquitto_log:/mosquitto/log
