name: Build and push multi-arch Docker image

on:
  push:
    paths:
      - 'base-compile/Dockerfile'
  pull_request:
    paths:
      - 'base-compile/Dockerfile'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push 20.04
        uses: docker/build-push-action@v2
        with:
          context: .
          file: base-compile/Dockerfile
          push: true
          tags: nguyendkn/base-compile:20.04
          platforms: linux/amd64,linux/arm64
          build-args: TAG=20.04

      - name: Build and push 22.04
        uses: docker/build-push-action@v2
        with:
          context: .
          file: base-compile/Dockerfile
          push: true
          tags: nguyendkn/base-compile:22.04
          platforms: linux/amd64,linux/arm64
          build-args: TAG=22.04
      
      - name: Build and push 18.04
        uses: docker/build-push-action@v2
        with:
          context: .
          file: base-compile/Dockerfile
          push: true
          tags: nguyendkn/base-compile:18.04
          platforms: linux/amd64,linux/arm64
          build-args: TAG=18.04

      - name: Logout of DockerHub
        run: docker logout